type = "checkout_ui_extension"
name = "checkout-ui-ext"

extension_points = [
  'Checkout::CustomerInformation::RenderAfter',
  'Checkout::ShippingMethods::RenderBefore',
  'Checkout::DeliveryAddress::RenderBefore',
  'Checkout::ShippingMethods::RenderAfter',
  'Checkout::CartLineDetails::RenderAfter',
  'Checkout::Reductions::RenderBefore',
  'Checkout::Reductions::RenderAfter',
  'Checkout::CartLines::RenderAfter',
  'Checkout::Actions::RenderBefore',
  'Checkout::PaymentMethod::Render',
  'Checkout::Contact::RenderAfter',
  'Checkout::Dynamic::Render',
  'Checkout::ThankYou::Dynamic::Render',
  'Checkout::OrderStatus::Dynamic::Render'
]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"

[capabilities]
network_access = true
block_progress = true
api_access = true

[settings]
[[settings.fields]]
key = "banner_title"
type = "single_line_text_field"
name = "Banner title"
description = "Enter a title for the banner"